on:
  pull_request: 
        types:
         - opened
         - assigned
         - unassigned
jobs:

  test:
   
    runs-on: ubuntu-latest
    name: A test job
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Test just output the message
      uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
